#!/bin/bash
# Nexus Forge Deployment Script
# Architecture: Firebase Gen 2 / Hosting
# Generated by Kaida OS v8.2 - Absolute Apex

set -e

echo "[KAIDA OS] Initiating Phase 2: Backend Cloud Deployment sequence."
echo "[KAIDA OS] Validating workspace directories..."

# Validate functions directory exists
if [ ! -d "functions" ]; then
    echo "[KAIDA OS: ERROR] 'functions' directory not found. Execute script from the project root."
    exit 1
fi

echo "[KAIDA OS] Entering logic core: functions/"
cd functions/

echo "[KAIDA OS] Materializing dependencies in requirements.txt..."
cat <<EOF > requirements.txt
firebase-functions
firebase-admin
google-generativeai
EOF

echo "[KAIDA OS] Dependencies written. Returning to root architecture..."
cd ..

echo "[KAIDA OS] Triggering global cloud deployment (functions, hosting)..."
# Larry will authenticate manually before this executes in his terminal
firebase deploy --only functions,hosting

echo "[KAIDA OS] Deployment matrix command execution finalized."
